export const USER_ROLES = {
  CITIZEN: 'citizen',
  VOLUNTEER: 'volunteer',
  WARD_OFFICER: 'ward_officer',
  ADMIN: 'admin'
} as const;

export const ISSUE_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  MEDIA_UPLOADED: 'MEDIA_UPLOADED',
  AI_ANALYSIS_RUNNING: 'AI_ANALYSIS_RUNNING',
  PENDING_TRUST_VALIDATION: 'PENDING_TRUST_VALIDATION',
  PENDING_DUPLICATE_CHECK: 'PENDING_DUPLICATE_CHECK',
  PENDING_SEVERITY_SCORING: 'PENDING_SEVERITY_SCORING',
  OPEN_FOR_COMMUNITY_VERIFICATION: 'OPEN_FOR_COMMUNITY_VERIFICATION',
  COMMUNITY_VERIFIED: 'COMMUNITY_VERIFIED',
  ASSIGNED_TO_AUTHORITY: 'ASSIGNED_TO_AUTHORITY',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLUTION_SUBMITTED: 'RESOLUTION_SUBMITTED',
  PENDING_CITIZEN_CONFIRMATION: 'PENDING_CITIZEN_CONFIRMATION',
  CLOSED_RESOLVED: 'CLOSED_RESOLVED',
  REJECTED: 'REJECTED',
  MERGED_WITH_EXISTING_ISSUE: 'MERGED_WITH_EXISTING_ISSUE',
  NEEDS_MANUAL_REVIEW: 'NEEDS_MANUAL_REVIEW',
  OVERDUE: 'OVERDUE',
  ESCALATED: 'ESCALATED',
  REOPENED: 'REOPENED',
  REQUIRES_FOLLOWUP: 'REQUIRES_FOLLOWUP'
} as const;

export const VOTE_TYPES = {
  EXISTS: 'EXISTS',
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_RESOLVED: 'ALREADY_RESOLVED',
  DUPLICATE: 'DUPLICATE',
  SEVERITY_HIGHER: 'SEVERITY_HIGHER',
  SEVERITY_LOWER: 'SEVERITY_LOWER'
} as const;

export const SEVERITY_LEVELS = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
} as const;

export const RESOLUTION_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  REJECTED: 'REJECTED',
  ACCEPTED: 'ACCEPTED',
  FOLLOWUP_REQUIRED: 'FOLLOWUP_REQUIRED'
} as const;

export const FEEDBACK_TYPES = {
  RESOLVED: 'RESOLVED',
  STILL_UNRESOLVED: 'STILL_UNRESOLVED',
  PARTIALLY_RESOLVED: 'PARTIALLY_RESOLVED',
  WRONG_ISSUE: 'WRONG_ISSUE',
  NEEDS_FOLLOWUP: 'NEEDS_FOLLOWUP'
} as const;

export const NOTIFICATION_TYPES = {
  ISSUE_SUBMITTED: 'ISSUE_SUBMITTED',
  NEEDS_MANUAL_REVIEW: 'NEEDS_MANUAL_REVIEW',
  COMMUNITY_VERIFIED: 'COMMUNITY_VERIFIED',
  DUPLICATE_MERGED: 'DUPLICATE_MERGED',
  ASSIGNED_TO_AUTHORITY: 'ASSIGNED_TO_AUTHORITY',
  IN_PROGRESS: 'IN_PROGRESS',
  SLA_WARNING: 'SLA_WARNING',
  ESCALATED: 'ESCALATED',
  RESOLUTION_SUBMITTED: 'RESOLUTION_SUBMITTED',
  CITIZEN_CONFIRMATION_REQUESTED: 'CITIZEN_CONFIRMATION_REQUESTED',
  ISSUE_CLOSED: 'ISSUE_CLOSED',
  ISSUE_REOPENED: 'ISSUE_REOPENED',
  COMMUNITY_VERIFICATION_REQUIRED: 'COMMUNITY_VERIFICATION_REQUIRED'
} as const;
