import { ISSUE_STATUS } from '../config/constants';
import { ApiError } from './ApiError';

type IssueStatus = keyof typeof ISSUE_STATUS;

// Define allowed transitions
const allowedTransitions: Record<string, string[]> = {
  [ISSUE_STATUS.DRAFT]: [ISSUE_STATUS.SUBMITTED],
  // SUBMITTED can only move to MEDIA_UPLOADED or NEEDS_MANUAL_REVIEW (not REJECTED, not ASSIGNED)
  [ISSUE_STATUS.SUBMITTED]: [ISSUE_STATUS.MEDIA_UPLOADED, ISSUE_STATUS.NEEDS_MANUAL_REVIEW],
  [ISSUE_STATUS.MEDIA_UPLOADED]: [
    ISSUE_STATUS.AI_ANALYSIS_RUNNING,
    ISSUE_STATUS.NEEDS_MANUAL_REVIEW,
  ],
  [ISSUE_STATUS.AI_ANALYSIS_RUNNING]: [
    ISSUE_STATUS.OPEN_FOR_COMMUNITY_VERIFICATION,
    ISSUE_STATUS.MERGED_WITH_EXISTING_ISSUE,
    ISSUE_STATUS.NEEDS_MANUAL_REVIEW,
    // NOTE: REJECTED and ASSIGNED_TO_AUTHORITY intentionally absent — Phase 1.1
  ],
  [ISSUE_STATUS.OPEN_FOR_COMMUNITY_VERIFICATION]: [
    ISSUE_STATUS.COMMUNITY_VERIFIED,
    ISSUE_STATUS.NEEDS_MANUAL_REVIEW,
    // NOTE: REJECTED and ASSIGNED_TO_AUTHORITY intentionally absent — must be community-verified first
  ],
  [ISSUE_STATUS.COMMUNITY_VERIFIED]: [
    ISSUE_STATUS.ASSIGNED_TO_AUTHORITY
  ],
  [ISSUE_STATUS.ASSIGNED_TO_AUTHORITY]: [
    ISSUE_STATUS.IN_PROGRESS,
    ISSUE_STATUS.ESCALATED,
    ISSUE_STATUS.NEEDS_MANUAL_REVIEW
  ],
  [ISSUE_STATUS.IN_PROGRESS]: [
    ISSUE_STATUS.RESOLUTION_SUBMITTED,
    ISSUE_STATUS.ESCALATED,
    ISSUE_STATUS.NEEDS_MANUAL_REVIEW
  ],
  [ISSUE_STATUS.RESOLUTION_SUBMITTED]: [
    ISSUE_STATUS.PENDING_CITIZEN_CONFIRMATION
  ],
  [ISSUE_STATUS.PENDING_CITIZEN_CONFIRMATION]: [
    ISSUE_STATUS.CLOSED_RESOLVED,
    ISSUE_STATUS.REOPENED,
    ISSUE_STATUS.REQUIRES_FOLLOWUP,
    ISSUE_STATUS.NEEDS_MANUAL_REVIEW
  ],
  [ISSUE_STATUS.REOPENED]: [
    ISSUE_STATUS.IN_PROGRESS,
    ISSUE_STATUS.ASSIGNED_TO_AUTHORITY,
    ISSUE_STATUS.RESOLUTION_SUBMITTED,
    ISSUE_STATUS.ESCALATED
  ],
  [ISSUE_STATUS.REQUIRES_FOLLOWUP]: [
    ISSUE_STATUS.IN_PROGRESS,
    ISSUE_STATUS.RESOLUTION_SUBMITTED,
    ISSUE_STATUS.ESCALATED
  ],
  [ISSUE_STATUS.NEEDS_MANUAL_REVIEW]: [
    ISSUE_STATUS.REJECTED,
    ISSUE_STATUS.OPEN_FOR_COMMUNITY_VERIFICATION,
    ISSUE_STATUS.COMMUNITY_VERIFIED,
    ISSUE_STATUS.ASSIGNED_TO_AUTHORITY,
    ISSUE_STATUS.CLOSED_RESOLVED
  ],
  [ISSUE_STATUS.MERGED_WITH_EXISTING_ISSUE]: [
    ISSUE_STATUS.REOPENED, // Can be unmerged by admin
  ],
  [ISSUE_STATUS.REJECTED]: [
    ISSUE_STATUS.NEEDS_MANUAL_REVIEW // Admin override
  ],
  [ISSUE_STATUS.CLOSED_RESOLVED]: [
    ISSUE_STATUS.REOPENED // Can be reopened if issues persist
  ],
  [ISSUE_STATUS.ESCALATED]: [
    ISSUE_STATUS.ASSIGNED_TO_AUTHORITY,
    ISSUE_STATUS.IN_PROGRESS,
    ISSUE_STATUS.RESOLUTION_SUBMITTED
  ],
  [ISSUE_STATUS.OVERDUE]: [ // Often a flag rather than a pure state, but if used as state:
    ISSUE_STATUS.ESCALATED,
    ISSUE_STATUS.IN_PROGRESS,
    ISSUE_STATUS.RESOLUTION_SUBMITTED
  ]
};

export const validateStatusTransition = (currentStatus: string, nextStatus: string): boolean => {
  if (currentStatus === nextStatus) return true; // No-op
  const allowed = allowedTransitions[currentStatus] || [];
  return allowed.includes(nextStatus);
};

export const transitionStatus = (issue: any, nextStatus: string) => {
  if (!validateStatusTransition(issue.status, nextStatus)) {
    throw new ApiError(400, `Invalid status transition from ${issue.status} to ${nextStatus}`);
  }
  issue.status = nextStatus;
};
